### ISSUE TITLE
Version 1.0.3 not available on npm

### ISSUE THREAD

**Issue by Eptis** [aomra015/ember-cli-zero-clipboard#17]
Hey all, 

I need version 1.0.3 because older versions break when running tests in PhantomJS. Can version 1.0.3 be pushed to NPM?

**Comment by seifsallam** [comment]
@aomra015 Can't find 1.0.3 on npm either

`version not found: ember-cli-zero-clipboard@1.0.3`

**Comment by aomra015** [comment]
@eptis & @seifsallam sorry about that -- this is resolved now.
