### ISSUE TITLE
Unavailable Zero Clipboard events

### ISSUE THREAD

**Issue by Ditofry** [aomra015/ember-cli-zero-clipboard#7]
First of all, thanks for providing this addon  :+1: 

It would be really awesome if some of the other events that Zero Clipboard broadcasts could be made available: https://github.com/zeroclipboard/zeroclipboard/blob/master/docs/api/ZeroClipboard.md#static-events

My use case was that I needed to hook into Zero Clipboard's `ready`, but in order to do so I had to overwrite `didInsertElement` so that I could bind to the `ready` event myself.

**Comment by aomra015** [comment]
@Ditofry this should be simple enough to do. When I get some free time I'll tackle this but of course a pull request is appreciated if you get to it first :)

**Comment by Ditofry** [comment]
Sounds good.  If I can I'll get you a pull request in the near future.  Thanks!
